version: '3.7'

services:
  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - 8069:8069
    networks:
      - odoo-network
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1 # for windows
    volumes:
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
    logging:
      options:
        max-size: 10m
    command: --dev=qweb,xml
    tty: true

  db:
    image: postgres:16
    networks:
      - odoo-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m

networks:
  odoo-network:

volumes:
  db-data:
