version: '3.7'

services:
  test:
    image: registry.3roots.live/odoo-root:18.0
    user: root
    depends_on:
      - test-db
    networks:
      - odoo-test-network
    environment:
      - COMPOSE_CONVERT_WINDOWS_PATHS=1 # for windows
    volumes:
      - ./odoo.local-test.conf:/etc/odoo/odoo.conf
      - ./addons:/mnt/addons
    logging:
      options:
        max-size: 10m
    command: test $OPTIONS
    tty: true

  test-db:
    image: postgres:16
    networks:
      - odoo-test-network
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - db-test-data:/var/lib/postgresql/data
    logging:
      options:
        max-size: 10m

networks:
  odoo-test-network:

volumes:
  db-test-data:
